services:
  epusdt:
    image: gmwallet/epusdt:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      EPUSDT_CONFIG: /app/conf/.env
      EPUSDT_DOCKER: "1"
    volumes:
      - ./conf:/app/conf
      - ./runtime:/app/runtime
    ports:
      - "8000:8000"
